const canvas = new fabric.Canvas('urbanCanvas', { backgroundColor: '#e0f7ff' });
        canvas.renderAll();
        function addStreet() { const street = new fabric.Rect({ left: 50, top: 200, width: 400, height: 10, fill: '#333333', selectable: true }); canvas.add(street); }
        function addRectangularBuilding() { const building = new fabric.Rect({ left: 300, top: 300, width: 60, height: 100, fill: '#7f8c8d', stroke: '#555555', strokeWidth: 1, selectable: true }); canvas.add(building); }
        function addLargeBuilding() { const building = new fabric.Rect({ left: 250, top: 250, width: 100, height: 150, fill: '#7f8c8d', stroke: '#555555', strokeWidth: 1, selectable: true }); canvas.add(building); }
        function addLShapedBuilding() { const buildingL = new fabric.Group([ new fabric.Rect({ left: 0, top: 0, width: 60, height: 100, fill: '#7f8c8d' }), new fabric.Rect({ left: 60, top: 0, width: 60, height: 40, fill: '#7f8c8d' }) ], { left: 300, top: 300, selectable: true }); canvas.add(buildingL); }
        function addUShapedBuilding() { const buildingU = new fabric.Group([ new fabric.Rect({ left: 0, top: 0, width: 40, height: 100, fill: '#7f8c8d' }), new fabric.Rect({ left: 40, top: 0, width: 60, height: 40, fill: '#7f8c8d' }), new fabric.Rect({ left: 100, top: 0, width: 40, height: 100, fill: '#7f8c8d' }) ], { left: 300, top: 300, selectable: true }); canvas.add(buildingU); }
        function addTShapedBuilding() { const buildingT = new fabric.Group([ new fabric.Rect({ left: 0, top: 0, width: 100, height: 40, fill: '#7f8c8d' }), new fabric.Rect({ left: 30, top: 40, width: 40, height: 100, fill: '#7f8c8d' }) ], { left: 300, top: 300, selectable: true }); canvas.add(buildingT); }
        function addHShapedBuilding() { const buildingH = new fabric.Group([ new fabric.Rect({ left: 0, top: 0, width: 40, height: 100, fill: '#7f8c8d' }), new fabric.Rect({ left: 40, top: 30, width: 60, height: 40, fill: '#7f8c8d' }), new fabric.Rect({ left: 100, top: 0, width: 40, height: 100, fill: '#7f8c8d' }) ], { left: 300, top: 300, selectable: true }); canvas.add(buildingH); }
        function addPlaza() { const plaza = new fabric.Circle({ left: 200, top: 200, radius: 50, fill: '#2ecc71', stroke: '#27ae60', strokeWidth: 2, selectable: true }); canvas.add(plaza); }
        function addTree() { const tree = new fabric.Circle({ left: 150, top: 150, radius: 20, fill: '#27ae60', stroke: '#145214', strokeWidth: 1, selectable: true }); canvas.add(tree); }
        function addGrassArea() { const grass = new fabric.Rect({ left: 400, top: 400, width: 80, height: 80, fill: '#27ae60', stroke: '#145214', strokeWidth: 1, selectable: true }); canvas.add(grass); }
        function addPark() { const park = new fabric.Rect({ left: 200, top: 300, width: 150, height: 100, fill: '#1e8449', stroke: '#145214', strokeWidth: 1, selectable: true }); canvas.add(park); }
        function addMetroLine() { const metroLine = new fabric.Line([50, 300, 600, 300], { stroke: '#ff0000', strokeWidth: 4, selectable: true }); canvas.add(metroLine); }
        function addTrainLine() { const trainLine = new fabric.Line([50, 400, 600, 400], { stroke: '#0000ff', strokeWidth: 4, strokeDashArray: [10, 5], selectable: true }); canvas.add(trainLine); }
        function addBusLine() { const busLine = new fabric.Line([50, 500, 600, 500], { stroke: '#ffa500', strokeWidth: 4, strokeDashArray: [5, 5], selectable: true }); canvas.add(busLine); }
        function addAirport() { const airport = new fabric.Triangle({ left: 400, top: 100, width: 40, height: 40, fill: '#e74c3c', selectable: true }); canvas.add(airport); }
        function addTransportStation() { const station = new fabric.Circle({ left: 500, top: 100, radius: 20, fill: '#2980b9', selectable: true }); canvas.add(station); }
        function addCommercialZone() { const commercialZone = new fabric.Rect({ left: 300, top: 400, width: 100, height: 50, fill: '#f39c12', stroke: '#e67e22', strokeWidth: 1, selectable: true }); canvas.add(commercialZone); }
        function addParkingLot() { const parkingLot = new fabric.Rect({ left: 100, top: 450, width: 120, height: 60, fill: '#95a5a6', stroke: '#7f8c8d', strokeWidth: 1, selectable: true }); canvas.add(parkingLot); }
        function addRecreationCenter() { const recCenter = new fabric.Rect({ left: 400, top: 450, width: 100, height: 60, fill: '#e74c3c', stroke: '#c0392b', strokeWidth: 1, selectable: true }); canvas.add(recCenter); }
        function addText() { const text = new fabric.IText('Texto aquí', { left: 200, top: 200, fontFamily: 'Arial', fontSize: 20, fill: '#000000', editable: true, selectable: true }); canvas.add(text); }
        function changeBackgroundColor() { const color = document.getElementById('backgroundColor').value; canvas.setBackgroundColor(color, canvas.renderAll.bind(canvas)); }
        function clearCanvas() { if (confirm("¿Estás seguro de que deseas borrar el lienzo?")) { canvas.clear(); const bgColor = document.getElementById('backgroundColor').value || '#e0f7ff'; canvas.setBackgroundColor(bgColor, canvas.renderAll.bind(canvas)); } }
        function exportCanvas() { const dataURL = canvas.toDataURL({ format: 'png', quality: 1.0 }); const link = document.createElement('a'); link.href = dataURL; link.download = 'plano_urbano.png'; link.click(); }